Errors translation 📰
bampakoa/angular-gr pull request #11
Opened 2022-04-15 11:33 UTC by kek-Sec

Let me know if it fits your standards , so I can translate the rest of the errors.

2022-05-03 09:33 UTC, bampakoa requested changes
@kek-Sec good job 💯 Έχω προσθέσει κάποιες αλλαγές inline για να τις δεις και να τις κάνεις commit αν σου φαίνονται σωστές 🙂

2022-05-03 09:33 UTC, bampakoa commented on aio/content/errors/NG0201.md
> +Εργαστείτε προς τα πίσω από το αντικείμενο όπου το σφάλμα δηλώνει ότι ο [πάροχος](guide/architecture-services) λείπει: `No provider for ${this}!`. Αυτό συνήθως συμβαίνει σε [υπηρεσίες](tutorial/toh-p
```suggestion
Ανατρέξτε προς τα πίσω από το αντικείμενο όπου το σφάλμα δηλώνει ότι ο [provider](guide/architecture-services) λείπει: `No provider for ${this}!`. Αυτό συνήθως συμβαίνει σε [services](tutorial/toh-pt4), που απαιτούν providers που δεν υπάρχουν.
```

2022-05-03 09:33 UTC, bampakoa commented on aio/content/errors/NG0201.md
> +Για να διορθώσετε το σφάλμα, βεβαιωθείτε ότι η υπηρεσία σας είναι εγγεγραμμένη στη λίστα παρόχων ενός `NgModule` ή ότι έχει το διακοσμητή `@Injectable` με την ιδιότητα `providedIn` στην κορυφή.
```suggestion
Για να διορθώσετε το σφάλμα, βεβαιωθείτε ότι το service σας είναι καταχωρημένο στη λίστα των providers ενός `NgModule` ή ότι έχει τον decorator `@Injectable` με την ιδιότητα `providedIn` στην κορυφή.
```

2022-05-03 09:33 UTC, bampakoa commented on aio/content/errors/NG0201.md
> +Η πιο συνηθισμένη λύση είναι να προσθέσετε έναν πάροχο στο `@Injectable` χρησιμοποιώντας το `providedIn`:
```suggestion
Η πιο συνηθισμένη λύση είναι να προσθέσετε έναν provider στο `@Injectable` χρησιμοποιώντας το `providedIn`:
```

2022-05-03 09:33 UTC, bampakoa commented on aio/content/errors/NG0300.md
> +Δύο ή περισσότερα στοιχεία χρησιμοποιούν τον ίδιο [επιλογέα στοιχείου](guide/component-overview#specifying-a-components-css-selector). Επειδή μπορεί να συσχετιστεί μόνο ένα στοιχείο με ένα στοιχείο,
```suggestion
Δύο ή περισσότερα components χρησιμοποιούν τον ίδιο [selector στοιχείου](guide/component-overview#specifying-a-components-css-selector). Επειδή μπορεί να συσχετιστεί μόνο ένα στοιχείο με ένα component, οι selectors πρέπει να είναι μοναδικοί για να αποφευχθεί η ασάφεια για την Angular.
```

2022-05-03 09:33 UTC, bampakoa commented on aio/content/errors/NG0300.md
> +Χρησιμοποιήστε το όνομα στοιχείου από το μήνυμα σφάλματος για να αναζητήσετε μέρη όπου χρησιμοποιείτε η [δήλωση επιλογέα](guide/architecture-components) στον κώδικα σας:
```suggestion
Χρησιμοποιήστε το όνομα στοιχείου από το μήνυμα σφάλματος για να αναζητήσετε μέρη όπου χρησιμοποιείτε τον ίδιο [ορισμό selector](guide/architecture-components) στον κώδικά σας:
```

2022-05-03 09:33 UTC, bampakoa commented on aio/content/errors/NG0300.md
> +Βεβαιωθείτε ότι κάθε στοιχείο έχει έναν μοναδικό επιλογέα CSS. Αυτό θα εγγυηθεί ότι η Angular αποδίδει το στοιχείο που περιμένετε.
```suggestion
Βεβαιωθείτε ότι κάθε component έχει έναν μοναδικό selector CSS. Αυτό θα εγγυηθεί ότι η Angular εμφανίζει το component που περιμένετε.
```

2022-05-03 09:33 UTC, bampakoa commented on aio/content/errors/NG0300.md
> +Εάν αντιμετωπίζετε προβλήματα με την εύρεση πολλών στοιχείων με αυτό το όνομα ετικέτας επιλογέα, ελέγξτε για στοιχεία από εισαγόμενες βιβλιοθήκες στοιχείων, όπως το Angular Material. Βεβαιωθείτε ότι
```suggestion
Εάν αντιμετωπίζετε προβλήματα με την εύρεση πολλαπλών components με αυτό το όνομα selector, ελέγξτε για components από εισαγόμενες βιβλιοθήκες, όπως το Angular Material. Βεβαιωθείτε ότι ακολουθείτε τις [βέλτιστες πρακτικές](guide/styleguide#component-selectors) για τους selectors σας για την αποφυγή αντικρούσεων.
```

2022-05-03 13:28 UTC, bampakoa commented
Εγώ σε ευχαριστώ @kek-Sec για την πολύτιμη βοήθεια 😄 Αν δεν είναι μεγάλος κόπος, μπορείς να βάλεις και το [reviewed tag](https://angular-gr.web.app/guide/reviewing-content#%CE%AD%CE%BB%CE%B5%CE%B3%CF%87%CE%BF%CF%82-%CF%80%CE%B5%CF%81%CE%B9%CE%B5%CF%87%CE%BF%CE%BC%CE%AD%CE%BD%CE%BF%CF%85-reviewed) στα αρχεία που μετέφρασες? Ξέχασα τελείως να το αναφέρω 😟 , με συγχωρείς.

2022-05-03 13:56 UTC, kek-Sec commented
fixed and ready to be deployed 😸

2022-05-03 20:02 UTC, bampakoa commented
@kek-Sec κάνω και τα υπόλοιπα suggestions commit που δεν έχουν γίνει. Είσαι οκ με αυτό?

2022-05-03 20:12 UTC, kek-Sec commented
Please, go ahead!

2022-05-07 19:17 UTC, bampakoa approved these changes

2022-05-07 19:20 UTC, merged