Translation/Feat: Understanding angular>Components>Overview
bampakoa/angular-gr pull request #6
Opened 2022-04-02 10:00 UTC by HRSArgyropoulos

**Summary**

- Translation of [Understanding angular>Components>Overview](https://angular-gr.web.app/guide/component-overview) page.
- Taxonomies translation table proposal

**Description**

As I was translating this topic/page and comparing it with the other PRs, it became more and more evident that a translation table for some terms might help in keeping the translation of this documentation consistent across all pages (as previously proposed by another member [lleenna](https://github.com/lleenna).
I have created a first implementation of this in the taxonomies-translation.md, thus let me know what you think about it (if find this necessary as well or you have any other suggestions). Thanks! 😃

2022-04-04 22:27 UTC, bampakoa commented
Καλησπέρα @HRSArgyropoulos 👋 Έχω μεταφέρει τον πολύ χρήσιμο πίνακά σου [εδώ](https://github.com/bampakoa/angular-gr/wiki/%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CF%8C-%CE%B3%CE%BB%CF%89%CF%83%CF%83%CE%AC%CF%81%CE%B9-%CF%8C%CF%81%CF%89%CE%BD). 

Πολύ καλη η ιδέα σου, σε ευχαριστώ πολύ 🙏

2022-04-05 17:24 UTC, HRSArgyropoulos commented
- Removed taxonomy markdown table from commit (as it got moved in the Wiki section of this repo)
- Updated the translation of this proposed PR topic to follow the new taxonomies translation from the wiki section.

2022-04-19 21:28 UTC, bampakoa requested changes
Καταπληκτική δουλειά @HRSArgyropoulos 👏 👏 Πολύ κατανοητή η συνολική μετάφραση 🚀

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +* Μια κλάση TypeScript που ορίζει τη συμπεριφορά
```suggestion
* Ένα TypeScript class που ορίζει τη συμπεριφορά
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +## Προϋποθέσεις
```suggestion
## Προαπαιτούμενα
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +Για να δημιουργήσετε ένα στοιχείο χρησιμοποιώντας το Angular CLI:
```suggestion
Για να δημιουργήσετε ένα component χρησιμοποιώντας το Angular CLI:
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +1. Απο το terminal παράθυρο, μεταβείτε στον κατάλογο που περιέχει την εφαρμογή σας.
```suggestion
1. Απο το terminal παράθυρο, μεταβείτε στον φάκελο που περιέχει την εφαρμογή σας.
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +* Ένα αρχείο προδιαγραφών δοκιμής, `<component-name>.component.spec.ts`
```suggestion
* Ένα test αρχείο, `<component-name>.component.spec.ts`
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +Για περισσότερες πληροφορίες, δείτε [ng generate component](cli/generate#component-command) στο εγχειρίδιο του Angular CLI.
```suggestion
Για περισσότερες πληροφορίες, δείτε [ng generate component](cli/generate#component-command) στην τεκμηρίωση του Angular CLI.
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +Αν και το Angular CLI είναι ο καλύτερος τρόπος για να δημιουργήσετε ένα Angular component, μπορείτε επίσης να δημιουργήσετε ένα στοιχείο με χειροκίνητο τρόπο.
```suggestion
Αν και το Angular CLI είναι ο καλύτερος τρόπος για να δημιουργήσετε ένα Angular component, μπορείτε επίσης να δημιουργήσετε ένα component με χειροκίνητο τρόπο.
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +Αυτή η ενότητα περιγράφει τον τρόπο δημιουργίας του βασικού component αρχείου σε ένα υπάρχον Angular project.
```suggestion
Αυτή η ενότητα περιγράφει τον τρόπο δημιουργίας του βασικού αρχείου component σε ένα υπάρχον Angular project.
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +1. Πλοηγηθείτε στον κατάλογο του Angular project.
```suggestion
1. Μεταβείτε στον φάκελο του δικού σας Angular project.
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +3. Στην κορυφή του αρχείου, προσθέστε την άκολουθη import δήλωση.
```suggestion
3. Στην κορυφή του αρχείου, προσθέστε το ακόλουθο import.
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +4. Μετά την `import` δήλωση, προσθέστε έναν `@Component` decorator.
```suggestion
4. Μετά το `import`, προσθέστε έναν `@Component` decorator.
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +8.  Προσθέστε μια `class` δήλωση που περιλαμβάνει τον κώδικα για το component.
```suggestion
8.  Προσθέστε ένα  `class` που περιλαμβάνει τον κώδικα για το component.
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +Ένα template είναι ένα μπλοκ HTML που λέει στο Angular πώς να απεικονίσει το component στην εφαρμογή σας.
```suggestion
Ένα template είναι ένα κομμάτι HTML που λέει στην Angular πώς να απεικονίσει το component στην εφαρμογή σας.
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +Ένα Angular component απαιτεί ένα template που ορίζεται με χρήση του `template` ή `templateUrl`. Δεν μπορείτε να έχετε και τις δύο δηλώσεις σε ένα component.
```suggestion
Ένα Angular component απαιτεί ένα template που ορίζεται με χρήση του `template` ή `templateUrl`. Δεν μπορείτε να έχετε και τις δύο ιδιότητες σε ένα component.
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +## Δήλωση του στυλ ενός component
```suggestion
## Δήλωση των στυλ ενός component
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +Δηλώστε τις χρήσεις στυλ του component για το template του με έναν από τους δύο τρόπους: με αναφορά σε ένα εξωτερικό αρχείο ή απευθείας μέσα στο component.
```suggestion
Δηλώστε τα στυλ του component για το template του με έναν από τους δύο τρόπους: με αναφορά σε ένα εξωτερικό αρχείο ή απευθείας μέσα στο component.
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +Η `styles` ιδιότητα λαμβάνει έναν πίνακα από συμβολοσειρές που περιέχουν τις δηλώσεις κανόνων CSS.
```suggestion
Η ιδιότητα `styles` δέχεται μια λίστα από strings που περιέχουν τους κανόνες CSS.
```

2022-04-19 21:28 UTC, bampakoa commented on aio/content/guide/component-overview.md
> +* Για περισσότερες πληροφορίες σχετικά με τα στυλ των components, ανατρέξτε στο [Στυλ του Component](guide/component-styles).
```suggestion
* Για περισσότερες πληροφορίες σχετικά με τα στυλ των components, δείτε [Στυλ του Component](guide/component-styles).
```

2023-06-22 09:27 UTC, merged