docs: fix Angular article (`το` --> `η`)
bampakoa/angular-gr pull request #8
Opened 2022-04-13 16:55 UTC by gkalpak

Angular is a platform (not a framework), so the right article in Greek is `η` (not `το`).

😛

2022-04-19 21:34 UTC, bampakoa requested changes
Καταπληκτικός όπως πάντα 🦸‍♂️ Σε ευχαριστώ πολύ. Θα ενημερώσεις και τα reviewed tags αν δεν βαριέσαι?

2022-04-19 21:34 UTC, bampakoa commented on aio/content/tutorial/toh-pt4.md
> +θα βασιστείτε στο [*dependency injection*](guide/dependency-injection) του Angular
```suggestion
θα βασιστείτε στο [*dependency injection*](guide/dependency-injection) της Angular
```

2022-04-21 09:05 UTC, gkalpak commented on aio/content/tutorial/toh-pt4.md
> +θα βασιστείτε στο [*dependency injection*](guide/dependency-injection) του Angular
Αααα 😱
Ξέχασα να αντικαταστήσω τα "του" σε "της" (έκανα μόνο τα "το"). Το διόρθωσα σε ένα νέο, fixup commit.

2022-04-21 09:06 UTC, gkalpak commented
Ενημέρωσα και τα reviewed tags :smiley:
PTAL

2022-04-27 16:18 UTC, bampakoa requested changes
@gkalpak εντόπισα 2 μικρές λεπτομέρειες. Εκτός αυτών, μου φαίνεται μια χαρά 👌

2022-04-27 16:18 UTC, bampakoa commented on aio/content/start/index.md
> +  Σε νέα components, η Angular Generator περιλαμβάνει ένα κενό `constructor()`, το interface `OnInit`, και την μέθοδο `ngOnInit()`.
```suggestion
  Τα νέα components περιλαμβάνουν ένα κενό `constructor()`, το interface `OnInit`, και την μέθοδο `ngOnInit()`.
```

Πως σου φαίνεται αυτό?

2022-04-27 16:18 UTC, bampakoa commented on aio/content/start/start-data.md
> +1. Για να καταχωρήσετε τους providers της Angular `HttpClient` σε όλη την εφαρμογή, προσθέστε το `HttpClientModule` στα `imports` του `@NgModule()` του `AppModule` .
```suggestion
1. Για να καταχωρήσετε τους providers του Angular `HttpClient` σε όλη την εφαρμογή, προσθέστε το `HttpClientModule` στα `imports` του `@NgModule()` του `AppModule` .
```

Αυτό νομίζω μπορεί να μείνει  ως έχει εφόσον αναφερόμαστε στο `HttpClient`

2022-04-29 16:31 UTC, bampakoa approved these changes
Ευχαριστώ @gkalpak 🙏

2022-04-29 16:32 UTC, merged